### ISSUE TITLE
太平通脚本提示调用接口失败

### ISSUE THREAD

**Issue by zc326** [yang7758258/ohhh_QL-Script#10]
账号[1]登录失败[50001]: 太平通用户接口调用失败

**Comment by yang7758258** [comment]
ck问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yang7758258/ohhh_QL-Script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月10日(星期三) 晚上10:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yang7758258/ohhh_QL-Script] 太平通脚本提示调用接口失败 (Issue #10)





 
账号[1]登录失败[50001]: 太平通用户接口调用失败
