### ISSUE TITLE
联通阅读可以修复下吗

### ISSUE THREAD

**Issue by hcliu987** [yang7758258/ohhh_QL-Script#13]

**Comment by hcliu987** [comment]
显示登录失败

**Comment by yang7758258** [comment]
更改appid

**Comment by hcliu987** [comment]
没明白。可以详细说明下吗

**Comment by hcliu987** [comment]
成功了谢谢

**Comment by JunLeB** [comment]
> 更改appid

如何更改 重新抓cookie吗

**Comment by JunLeB** [comment]
> 成功了谢谢

麻烦问一下 改哪里

**Comment by hcliu987** [comment]
重新抓有个参数叫appid的，然后在代码里找一下appid的变量名，看看这个变量名的参数写死的，自己改一下应该就可以。我是这样操作的

**Comment by JunLeB** [comment]
> 重新抓有个参数叫appid的，然后在代码里找一下appid的变量名，看看这个变量名的参数写死的，自己改一下应该就可以。我是这样操作的

非常感谢
