### ISSUE TITLE
兴攀农场跑一半身份信息失效

### ISSUE THREAD

**Issue by zjk2017** [yang7758258/ohhh_QL-Script#14]
============= 账号[1]开始任务 =============
🌸账号[1]🕊签到成功-获得5积分🎉
🌸账号[1]🕊任务1完成[操作成功]🎉
🌸账号[1]🕊任务1领取[操作成功],获得雨水20🎉
🌸账号[1]🕊任务2完成[操作成功]🎉
🌸账号[1]🕊任务2领取[操作成功],获得肥料10🎉
🌸账号[1]任务3完成失败:任务未开启❌
🌸账号[1]任务3领取失败:奖励已领取或任务未完成❌
🌸账号[1]任务4完成失败:任务未开启❌
🌸账号[1]任务4领取失败:奖励已领取或任务未完成❌
🌸账号[1]🕊任务5完成[操作成功]🎉
🌸账号[1]任务5领取失败:已签到❌
🌸账号[1]🕊任务6完成[操作成功]🎉
🌸账号[1]任务6领取失败:今天已签到，请明天在来❌
🌸账号[1]🕊任务7完成[操作成功]🎉
🌸账号[1]任务7领取失败:没到时间，无法签到❌
🌸账号[1]🕊任务8完成[操作成功]🎉
🌸账号[1]任务8领取失败:没到时间，无法签到❌
🌸账号[1]🕊任务9完成[操作成功]🎉
🌸账号[1]任务9领取失败:没到时间，无法签到❌
🌸账号[1]🕊任务10完成[操作成功]🎉
🌸账号[1]任务10领取失败:已签到❌
🌸账号[1]任务11完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务11领取失败:手速太快，请稍后重试！❌
🌸账号[1]任务12完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务12领取失败:手速太快，请稍后重试！❌
🌸账号[1]任务13完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务13领取失败:手速太快，请稍后重试！❌
🌸账号[1]任务14完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务14领取失败:手速太快，请稍后重试！❌
🌸账号[1]任务15完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务15领取失败:手速太快，请稍后重试！❌
🌸账号[1]任务16完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务16领取失败:身份信息失效，请重新登录❌
🌸账号[1]施肥失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]查询🔍失败:身份信息失效，请重新登录❌
账号[1]随机等待4.766秒...

🔔vx兴攀农场,结束!🕛65.088秒

**Comment by yang7758258** [comment]
重新抓ck呗发自我的 iPhone在 2024年9月3日，16:30，zjk2017 ***@***.***> 写道：﻿
============= 账号[1]开始任务 =============
🌸账号[1]🕊签到成功-获得5积分🎉
🌸账号[1]🕊任务1完成[操作成功]🎉
🌸账号[1]🕊任务1领取[操作成功],获得雨水20🎉
🌸账号[1]🕊任务2完成[操作成功]🎉
🌸账号[1]🕊任务2领取[操作成功],获得肥料10🎉
🌸账号[1]任务3完成失败:任务未开启❌
🌸账号[1]任务3领取失败:奖励已领取或任务未完成❌
🌸账号[1]任务4完成失败:任务未开启❌
🌸账号[1]任务4领取失败:奖励已领取或任务未完成❌
🌸账号[1]🕊任务5完成[操作成功]🎉
🌸账号[1]任务5领取失败:已签到❌
🌸账号[1]🕊任务6完成[操作成功]🎉
🌸账号[1]任务6领取失败:今天已签到，请明天在来❌
🌸账号[1]🕊任务7完成[操作成功]🎉
🌸账号[1]任务7领取失败:没到时间，无法签到❌
🌸账号[1]🕊任务8完成[操作成功]🎉
🌸账号[1]任务8领取失败:没到时间，无法签到❌
🌸账号[1]🕊任务9完成[操作成功]🎉
🌸账号[1]任务9领取失败:没到时间，无法签到❌
🌸账号[1]🕊任务10完成[操作成功]🎉
🌸账号[1]任务10领取失败:已签到❌
🌸账号[1]任务11完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务11领取失败:手速太快，请稍后重试！❌
🌸账号[1]任务12完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务12领取失败:手速太快，请稍后重试！❌
🌸账号[1]任务13完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务13领取失败:手速太快，请稍后重试！❌
🌸账号[1]任务14完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务14领取失败:手速太快，请稍后重试！❌
🌸账号[1]任务15完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务15领取失败:手速太快，请稍后重试！❌
🌸账号[1]任务16完成失败:手速太快，请稍后重试！❌
🌸账号[1]任务16领取失败:身份信息失效，请重新登录❌
🌸账号[1]施肥失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]浇水失败:身份信息失效，请重新登录❌
🌸账号[1]查询🔍失败:身份信息失效，请重新登录❌
账号[1]随机等待4.766秒...
🔔vx兴攀农场,结束!🕛65.088秒

**Comment by nameyq11** [comment]
脚本没人打理了。散了吧。
