### ISSUE TITLE
海天更新最新版本还是报错 也米有签到成功

### ISSUE THREAD

**Issue by jiuchu** [yang7758258/ohhh_QL-Script#3]
===== 当前版本：1.0.1 📌 最新版本：1.0.0 ======

============= 账号[1]开始任务 =============

"getaddrinfo ENOTFOUND cmallapi.haday.cn"

❗️vx海天美味馆,错误!

TypeError: Cannot use 'in' operator to search for 'activity_code' in undefined
    at SignTask (/ql/scripts/htmwg.js:120:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async userTask (/ql/scripts/htmwg.js:72:5)
    at async main (/ql/scripts/htmwg.js:60:9)
    at async /ql/scripts/htmwg.js:25:5

[liulanjifen]请求错误(ENOTFOUND)，重试第1次

**Comment by yang7758258** [comment]
等更新

**Comment by yang7758258** [comment]
> ===== 当前版本：1.0.1 📌 最新版本：1.0.0 ======
> 
> ============= 账号[1]开始任务 =============
> 
> "getaddrinfo ENOTFOUND cmallapi.haday.cn"
> 
> ❗️vx海天美味馆,错误!
> 
> TypeError: Cannot use 'in' operator to search for 'activity_code' in undefined at SignTask (/ql/scripts/htmwg.js:120:28) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async userTask (/ql/scripts/htmwg.js:72:5) at async main (/ql/scripts/htmwg.js:60:9) at async /ql/scripts/htmwg.js:25:5
> 
> [liulanjifen]请求错误(ENOTFOUND)，重试第1次

更新了，再拉取测试看看

**Comment by jiuchu** [comment]
> > ===== 当前版本：1.0.1 📌 最新版本：1.0.0 ======
> > ============= 账号[1]开始任务 =============
> > "getaddrinfo ENOTFOUND cmallapi.haday.cn"
> > ❗️vx海天美味馆,错误!
> > TypeError: Cannot use 'in' operator to search for 'activity_code' in undefined at SignTask (/ql/scripts/htmwg.js:120:28) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async userTask (/ql/scripts/htmwg.js:72:5) at async main (/ql/scripts/htmwg.js:60:9) at async /ql/scripts/htmwg.js:25:5
> > [liulanjifen]请求错误(ENOTFOUND)，重试第1次
> 
> 更新了，再拉取测试看看

===== 当前版本：1.0.4 📌 最新版本：1.0.1 ======


============= 账号[1]开始任务 =============


 签到 失败了!请稍后尝试!!
服务器卡爆啦

🌸账号[1]签到失败,可能已经签到❌

[liulanjifen]请求错误(ENOTFOUND)，重试第1次

[liulanjifen]请求错误(ENOTFOUND)，重试第2次

[liulanjifen]请求错误(ENOTFOUND)，重试第3次

TypeError: Cannot read properties of undefined (reading 'statusCode')
    at request (/ql/scripts/htmwg.js:550:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async liulanjifen (/ql/scripts/htmwg.js:250:49)
    at async userTask (/ql/scripts/htmwg.js:74:5)
    at async main (/ql/scripts/htmwg.js:60:9)
    at async /ql/scripts/htmwg.js:25:5

[lingjihuijihui]请求错误(ENOTFOUND)，重试第1次

[lingjihuijihui]请求错误(ENOTFOUND)，重试第2次

[lingjihuijihui]请求错误(ENOTFOUND)，重试第3次

TypeError: Cannot read properties of undefined (reading 'statusCode')
    at request (/ql/scripts/htmwg.js:550:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async lingjihuijihui (/ql/scripts/htmwg.js:199:49)
    at async userTask (/ql/scripts/htmwg.js:76:5)
    at async main (/ql/scripts/htmwg.js:60:9)
    at async /ql/scripts/htmwg.js:25:5


 兑机会 失败了!请稍后尝试!!
服务器卡爆啦
🌸账号[1]🕊积分兑抽奖 兑换失败❌


 兑机会 失败了!请稍后尝试!!
服务器卡爆啦

**Comment by jiuchu** [comment]
现在报错信息变成上面那样了

**Comment by jiuchu** [comment]
还有救吗

**Comment by yang7758258** [comment]
> 还有救吗

目前测试是正常运行的
