### ISSUE TITLE
zippo抓的ck显示失效

### ISSUE THREAD

**Issue by GitLiyc** [yang7758258/ohhh_QL-Script#5]
刚抓到的authorization 变量也创建了名字为zippo，值也去掉了Beaer
还是报错
===== 当前版本：1.0.4 📌 最新版本：1.0.4 ======

完成积分签到与收藏任务

========== 共找到 1 个账号 ==========

📌📌📌📌📌📌📌📌登录/CK检测📌📌📌📌📌📌📌📌

账号[1]查询失败,可能是CK失效!

📌📌📌📌📌📌📌📌开始签到📌📌📌📌📌📌📌📌

账号[1]签到成功🎉

📌📌📌📌📌📌📌📌取消收藏📌📌📌📌📌📌📌📌

好像出了点小问题

📌📌📌📌📌📌📌📌收藏📌📌📌📌📌📌📌📌

好像出了点小问题

📌📌📌📌📌📌📌📌开始领取每日收藏奖励📌📌📌📌📌📌📌📌

📌📌📌📌📌📌📌📌当前积分查询📌📌📌📌📌📌📌📌

账号[1]当前积分为💰[undefined]🎉
账号[1]查询失败,可能是CK失效!

🔔zippo,结束!🕛9.765秒

**Comment by yang7758258** [comment]
不需要去掉Beaer

**Comment by GitLiyc** [comment]
> 不需要去掉Beaer

加上了也显示这个，但是我又抓了好几次，Auth没问题啊

**Comment by yang7758258** [comment]
测试没问题的，请检查你自己的环境
![IMG_1951](https://github.com/yang7758258/ohhh154/assets/43715693/084678fc-69ed-40de-a008-5c54a3213f35)

**Comment by GitLiyc** [comment]
> 测试没问题的，请检查你自己的环境
> 
> ![IMG_1951](https://github.com/yang7758258/ohhh154/assets/43715693/084678fc-69ed-40de-a008-5c54a3213f35)
> 
> 

好的我再看看
