### ISSUE TITLE
好奇车生活好像只做签到任务啊

### ISSUE THREAD

**Issue by jiuchu** [yang7758258/ohhh_QL-Script#6]
============= 账号[1]开始任务 =============
🌸账号[1]🕊今日签到状态为:[true]🎉
🌸账号[1]任务success
🕊任务编号:662805299354165248🎉
🌸账号[1]任务success
🕊任务编号:662805189626974208🎉
🌸账号[1]任务success
🕊任务编号:662793252641984512🎉
🌸账号[1]任务success
🕊任务编号:662794321581330432🎉
🌸账号[1]任务success
🕊任务编号:662794237938524160🎉
🌸账号[1]任务success
🕊任务编号:662794135429734400🎉
🌸账号[1]任务success
🕊任务编号:662805119309467648🎉
🌸账号[1]任务success
🕊任务编号:662805251388100608🎉
🌸账号[1]🕊抽奖状态:[false]🎉
🌸账号[1]总积分💰:[2092]🎉
账号[1]随机等待2.4秒...

**Comment by yang7758258** [comment]
请手动抽一次或者再跑一次

**Comment by jiuchu** [comment]
> ============= 账号[1]开始任务 ============= 🌸账号[1]🕊今日签到状态为:[true]🎉 🌸账号[1]任务success 🕊任务编号:662805299354165248🎉 🌸账号[1]任务success 🕊任务编号:662805189626974208🎉 🌸账号[1]任务success 🕊任务编号:662793252641984512🎉 🌸账号[1]任务success 🕊任务编号:662794321581330432🎉 🌸账号[1]任务success 🕊任务编号:662794237938524160🎉 🌸账号[1]任务success 🕊任务编号:662794135429734400🎉 🌸账号[1]任务success 🕊任务编号:662805119309467648🎉 🌸账号[1]任务success 🕊任务编号:662805251388100608🎉 🌸账号[1]🕊抽奖状态:[false]🎉 🌸账号[1]总积分💰:[2092]🎉 账号[1]随机等待2.4秒...
